### ISSUE TITLE
Attach sound to a sound emitter to control the distance. *New Feature*

### ISSUE THREAD

**Issue by John3** [StefanLundmark/Torque3D_Awesomium#3]
Hi!

Attach sound to a sound emitter to control the distance.

http://www.garagegames.com/community/blogs/view/22068/3#comment-200287

**Comment by StefanLundmark** [comment]
Hi John!

I'm afraid this isn't possible because of how Awesomium is designed. The sound you hear from it is played from another process, the same one which renders the content for you and passes it along to Awesomium trough IPC calls. 

Currently we have no access to this data, so you'd have to ask the Aeesomium guys to expose this and if they do I'll be glad to implement it in the pack. :)

**Comment by John3** [comment]
ok better close this, is not related to T3D_Awesomium, I mean your work. Thanks Stefan.
