### ISSUE TITLE
full source code

### ISSUE THREAD

**Issue by huhorler** [StefanLundmark/Torque3D_Awesomium#4]
Do you have the demo full source code? I want to learn about it.thank you

**Comment by John3** [comment]
hey @huhorler please check it out in my fork: https://github.com/John3/Torque3D_Awesomium

**Comment by huhorler** [comment]
I add the SDK and the code to the engine step to step,but the material is not render.So I want to compare the engine code changed from the demo and mine,

**Comment by StefanLundmark** [comment]
Hi guys, 

There has been a few changes since then but none that should break compatibility with the demo. Are the render target names correct? These might have changed when GG patched in a few new features in procedural materials which affected how the mappings work.

Do the GUI awesomium surfaces render normally? 

If you're comfortable stepping trough C++ then you can place a breakpoint in AwContext::Render and see if the surface is null.

**Comment by huhorler** [comment]
the class AwContext do not has AwContext::Render method.

**Comment by StefanLundmark** [comment]
I'm writing from memory on my phone, I'll reply to this thread when I get home.

**Comment by huhorler** [comment]
Thank you ,and you can send email to 446468979@qq.com

**Comment by StefanLundmark** [comment]
Check if the surface is null in AwContext::copyToTexture(). You can place a breakpoint in Visual Studio.

I'll take a look at this as soon as I get some spare time. Any details on how you reproduce this would be appreciated! :)

**Comment by huhorler** [comment]
I find the AwManager::OnPostRender is not implemented.And the AwTextureTarget::onRender is not run.Is that problem?

**Comment by StefanLundmark** [comment]
Sorry, I didn't get a notification for this message.

OnPostRender shouldn't be implemented. AwTextureTarget::onRender should run obviously, so that's bad news if it doesn't run. Can you provide reproduction steps?

**Comment by StefanLundmark** [comment]
Closing this as no response has been given since last October. If you still have this problem please provide reproduction steps.
